/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup.route'
import { Route as SigninRouteImport } from './routes/signin.route'
import { Route as EditorRouteImport } from './routes/editor.route'
import { Route as IndexRouteImport } from './routes/index.route'

// Create/Update Routes

const SignupRouteRoute = SignupRouteImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const SigninRouteRoute = SigninRouteImport.update({
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any)

const EditorRouteRoute = EditorRouteImport.update({
  path: '/editor',
  getParentRoute: () => rootRoute,
} as any)

const IndexRouteRoute = IndexRouteImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRouteRoute,
  EditorRouteRoute,
  SigninRouteRoute,
  SignupRouteRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/editor",
        "/signin",
        "/signup"
      ]
    },
    "/": {
      "filePath": "index.route.tsx"
    },
    "/editor": {
      "filePath": "editor.route.tsx"
    },
    "/signin": {
      "filePath": "signin.route.tsx"
    },
    "/signup": {
      "filePath": "signup.route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
